/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetre;

import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import models.Appareil;
import models.Batterie;
import models.Client;
import models.Panneau;
import remote.AppareilRemote;
import remote.BatterieRemote;
import remote.ClientRemote;
import remote.PanneauRemote;

/**
 *
 * @author Tsiory
 */
public class FenetreDevis extends javax.swing.JFrame {

    @EJB
    private static BatterieRemote batterieImpl;

    @EJB
    private static AppareilRemote appareilImpl;

    @EJB
    private static ClientRemote clientImpl;

    @EJB
    private static PanneauRemote panneauImpl;

    /**
     * Creates new form FenetreDevis
     */
    public final List<Appareil> list = new ArrayList<>();
    private List<Batterie> batterieList;
    public DefaultListModel<String> model = new DefaultListModel<String>();

    public FenetreDevis() {
        initComponents();
        this.setListPanneau();
        this.setListBatterie();
        this.listeappareilmaison.setModel(model);
    }

    public void addAppareil(Appareil appareil) {
        this.list.add(appareil);
    }

    public void setListPanneau() {
        List<Panneau> listPanneau = FenetreDevis.panneauImpl.findAll();
        String[] list = new String[listPanneau.size()];
        for (int i = 0; i < listPanneau.size(); i++) {
            list[i] = listPanneau.get(i).getNom() + " " + listPanneau.get(i).getPuissance() + " " + listPanneau.get(i).getPrix();
        }
   
    }

    public void setListBatterie() {
        List<Batterie> listBatterie = FenetreDevis.batterieImpl.findAll();
        String[] _list = new String[listBatterie.size()];
        for (int i = 0; i < listBatterie.size(); i++) {
            _list[i] = listBatterie.get(i).getNom() + " " + listBatterie.get(i).getAmperage() + "Ah " + listBatterie.get(i).getVoltage();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Maison = new javax.swing.JPanel();
        proposer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listeappareilmaison = new javax.swing.JList<>();
        Details = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refClient = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomClient = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        ajouterappareil = new javax.swing.JButton();
        refdemande = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Maison.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Maison"));

        proposer.setText("Demander");
        proposer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proposerMouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(listeappareilmaison);

        javax.swing.GroupLayout MaisonLayout = new javax.swing.GroupLayout(Maison);
        Maison.setLayout(MaisonLayout);
        MaisonLayout.setHorizontalGroup(
            MaisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaisonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proposer)
                .addContainerGap(198, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        MaisonLayout.setVerticalGroup(
            MaisonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaisonLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(proposer)
                .addContainerGap())
        );

        Details.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Reference Client"));

        jLabel1.setText("Ref :");

        jLabel2.setText("Nom : ");

        jLabel3.setText("Adresse :");

        adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresseActionPerformed(evt);
            }
        });

        jLabel4.setText("Prenom :");

        ajouterappareil.setText("Ajouter appareil");
        ajouterappareil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterappareilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DetailsLayout = new javax.swing.GroupLayout(Details);
        Details.setLayout(DetailsLayout);
        DetailsLayout.setHorizontalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DetailsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ajouterappareil))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetailsLayout.createSequentialGroup()
                        .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prenom, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(nomClient)
                            .addComponent(refdemande, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DetailsLayout.setVerticalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refClient)
                    .addComponent(refdemande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(ajouterappareil)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Maison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Maison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresseActionPerformed

    private void ajouterappareilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterappareilMouseClicked
        // TODO add your handling code here:
        new DetailsAppareil(this).show();
    }//GEN-LAST:event_ajouterappareilMouseClicked

    private void proposerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proposerMouseClicked
        String ref = this.refdemande.getText();
        String nom = this.nomClient.getText();
        String _prenom = this.prenom.getText();
        String _adresse = this.adresse.getText();
        LocalDate datedemande = LocalDate.now();
        Client client = new Client(0, ref, nom, _prenom, _adresse, datedemande);
        FenetreDevis.clientImpl.save(client);
        int lastid = FenetreDevis.clientImpl.getLastId();
        for (Appareil appareil : list) {
            appareil.setClient_id(lastid);
            FenetreDevis.appareilImpl.save(appareil);
        }
        JOptionPane.showMessageDialog(this, "Demande envoye", "Insert", JOptionPane.DEFAULT_OPTION);
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create("http://localhost:8484/client-devis/index.php?action=devisclient&&client_id=23"));
        } catch (IOException ex) {
            Logger.getLogger(DetailsAppareil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_proposerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDevis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDevis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDevis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDevis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDevis().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Details;
    private javax.swing.JPanel Maison;
    private javax.swing.JTextField adresse;
    private javax.swing.JButton ajouterappareil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listeappareilmaison;
    private javax.swing.JTextField nomClient;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton proposer;
    private javax.swing.JLabel refClient;
    private javax.swing.JTextField refdemande;
    // End of variables declaration//GEN-END:variables
}
